version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: template-api-dev
    image: template-api-dev
    # Uncomment this line in case you are in M1
    # platform: linux/amd64
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
    networks:
      - 'app-network'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/template-api?schema=public

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - 'app-network'

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
