version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ./.docker/entrypoint.sh
    container_name: template-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '7100:7100'
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    networks:
      - 'app-network'
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - 'app-network'

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
