version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ./.docker/entrypoint.dev.sh
    container_name: template-app
    ports:
      - '7100:7100'
    volumes:
      - .:/usr/src/app
    networks:
      - 'app-network'
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - 'app-network'

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
