FROM node:12.14-alpine3.11

RUN apk add --no-cache bash

RUN touch /root/.bashrc | echo "PS1='\w\$ '" >> /root/.bashrc

WORKDIR /usr/src/app

EXPOSE 7100

ENTRYPOINT [ "sh", "./.docker/entrypoint.dev.sh" ]
