name: Lint Repo

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v3

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run prisma generate
        run: yarn prisma:generate

      - name: Lint changed files
        run: yarn eslint $(printf "${{ env.GIT_DIFF_FILTERED }}" | tr " |\'" "\n" | grep -E ".ts$")
        if: env.GIT_DIFF && env.GIT_DIFF_FILTERED
