name: On pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr_analysis:
    name: PR Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run prisma generate
        run: yarn prisma:generate

      - name: Unit tests
        run: yarn test

      - name: E2E tests
        run: yarn test:e2e
