name: Super linter

on:
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run prisma generate
        run: yarn prisma:generate

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_TSX: false
          LINTER_RULES_PATH: /
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_SQL: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_JSCPD: false
          VALIDATE_JAVASCRIPT_ES: false
          TYPESCRIPT_DEFAULT_STYLE: prettier
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
